### ISSUE TITLE
SignTool Error: File not found

### ISSUE THREAD

**Issue by bra1n** [Levminer/trusted-signing-cli#1]
Hi,
I'm having issues getting the beforeBundleCommand to execute correctly. It seems like the signtool.exe is never able to find the appropriate built file to sign. Here's the Github Action config I'm using:

```yaml
      - name: install dependencies (windows only)
        if: matrix.platform == 'windows-latest'
        shell: bash
        env:
          BEFORE_BUNDLE_COMMAND: trusted-signing-cli -e "https://weu.codesigning.azure.net/" -a "my-app" -c "my-app" "${{ github.workspace }}\src-tauri\target\release\my-app.exe"
        run: |
          cd "$GITHUB_WORKSPACE"
          cat './src-tauri/tauri.conf.json' | jq '.build += {"beforeBundleCommand": env.BEFORE_BUNDLE_COMMAND}' > './src-tauri/temp.json' && mv './src-tauri/temp.json' './src-tauri/tauri.conf.json'
          cargo install trusted-signing-cli
``` 
And here's the output from the runner:
```
[...]
Built application at: D:\a\my-app\my-app\src-tauri\target\release\my-app.exe
    Running beforeBundleCommand `trusted-signing-cli -e "https://weu.codesigning.azure.net/" -a "my-app" -c "my-app" "D:\a\my-app\my-app\src-tauri\target\release\my-app.exe"`
[
  {
    "cloudName": "AzureCloud",
    "homeTenantId": "***",
    "id": "...",
    "isDefault": true,
    "managedByTenants": [],
    "name": "...",
    "state": "Enabled",
    "tenantId": "***",
    "user": {
      "name": "***",
      "type": "servicePrincipal"
    }
  }
]
SignTool Error: File not found: "D:\a\my-app\my-app\src-tauri\target\release\my-app.exe"
Number of files successfully Signed: 0
Number of warnings: 0
Number of errors: 1
thread 'main' panicked at C:\Users\runneradmin/.cargo\registry\src\index.crates.io-6f17d22bba15001f\trusted-signing-cli-0.2.0\src/main.rs:159:10:
called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: "command [\"C:\\\\Program Files (x86)\\\\Windows Kits\\\\10\\\\bin\\\\10.0.22000.0\\\\x64\\\\signtool.exe\", \"sign\", \"/v\", \"/fd\", \"SHA256\", \"/tr\", \"[http://timestamp.acs.microsoft.com\](http://timestamp.acs.microsoft.com/)", \"/td\", \"SHA256\", \"/dlib\", \"C:\\\\Users\\\\runneradmin\\\\.trusted-signing-cli\\\\lib\\\\bin\\\\x64\\\\Azure.CodeSigning.Dlib.dll\", \"/dmdf\", \"C:\\\\Users\\\\runneradmin\\\\.trusted-signing-cli\\\\metadata.json\", \"\\\"D:\\\\a\\\\my-app\\\\my-app\\\\src-tauri\\\\target\\\\release\\\\my-app.exe\\\"\"] exited with code 1" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
    Error beforeBundleCommand `trusted-signing-cli -e "https://weu.codesigning.azure.net/" -a "my-app" -c "my-app" "D:\a\my-app\my-app\src-tauri\target\release\my-app.exe"` failed with exit code 101
```
When I manually build the app with Windows, I can find the `my-app.exe` in /src-tauri/target/release, as well as a `my_app.exe` (underscore instead of dash) in /src-tauri/target/release/deps, but neither path works. Any idea how to fix this?
